name: gtm
description: Flutter plugin for Google Tag Manager, A solution that allows you to manage various tags such as analysis, 
  advertising performance measurement, and affiliate marketing tracking.
repository: https://github.com/Heewookji/gtm/tree/main/gtm
issue_tracker: https://github.com/Heewookji/gtm/issues
version: 0.1.2

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: gtm_android
      ios:
        default_package: gtm_ios

dependencies:
  flutter:
    sdk: flutter
  gtm_platform_interface: ^0.0.6
  gtm_android: ^0.1.0
  gtm_ios: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  plugin_platform_interface: ^2.1.4

