name: gtm_android
description: Flutter gtm plugin android
repository: https://github.com/Heewookji/gtm
issue_tracker: https://github.com/Heewookji/gtm/issues
version: 0.1.0

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: gtm
    platforms:
      android:
        package: kr.heewook.gtm_android
        dartPluginClass: GtmAndroid
        pluginClass: GtmAndroidPlugin
dependencies:
  flutter:
    sdk: flutter
  gtm_platform_interface: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
